Added port to modbus tcp config
nio-blocks/modbus pull request #47
Opened 2018-10-29 19:19 UTC by sploders101

self._clients has keys in the format of "{{host}}:{{port}}" now, and a port field has been added to the block configuration

2018-10-29 20:49 UTC, shadetree01010100 requested changes
Thank you for the Pull Request! This is a great feature to add, but a few changes will be needed before we can merge this.

In addition to updating spec.json, README.md needs to be updated to describe the new property, as well. You can use the CLI tool `nio buildreadme` from the block directory to do this automatically.

The unit tests also need to be updated, currently they cannot pass. If you are not familiar with unit testing in python, pytest is a commonly used runner https://docs.pytest.org/en/latest/ To use it you need to run `pytest tests` from the block directory, and pytest will discover and execute the tests insides `tests/`. if you try this with your branch, 8 of the 19 tests fail. The block test case is defined here https://github.com/niolabs/nio/blob/master/nio/testing/block_test_case.py and provides some helpful assertions in addition to those inherited from https://docs.python.org/3/library/unittest.mock.html

The test should be updated to cover the new property, both if the block is configured with a static `502` for example, and also if it evaluates with the incoming signal, for example `{{ $port }}` where the incoming signal includes the attribute `port` with an integer value, similar to what's happening inside `test_multiple_tests` here https://github.com/nio-blocks/modbus/blob/master/tests/test_modbus_tcp_block.py#L74

2018-10-30 13:10 UTC, sploders101 commented
Sounds good! I am in the service department today, so I'll make these changes and resubmit this evening

2018-11-05 19:03 UTC, sploders101 commented
I used the nio updatereadme tool to update the readme, and fixed the bug with reconnecting. 
I had attempted to use the properties of the client itself to avoid string manipulation with the index.
```python
self._connect_to_host(self._clients[host].host, self._clients[host].port)
```
However, I must have misunderstood pymodbus3's code, because those properties don't exist. I updated the branch with a version that splits the index, and converts the port to an int before passing them on.

2018-11-05 20:26 UTC, shadetree01010100 approved these changes
This looks great, thanks for taking the time to contribute! I left a suggestion for your reference as you learn more Python, but the code works great!

2018-11-05 20:26 UTC, shadetree01010100 commented on modbus_tcp_block.py
> +                indexVars = index.split(":")
in Python you can unpack an iterable, such as returned by `split`, into multiple values, like this:
```
for client in self._clients:
    host, port = client.split(":")
    self._connect_to_host(host, int(port))
```

2018-11-05 20:28 UTC, merged